### ISSUE TITLE
[GNOME] Dash launch icon is blurry

### ISSUE THREAD

**Issue by ghost** [chistota/rospo-icon-theme#1]
Hello, thank your for this nice remix of Papirus.

I found this issue in Gnome-Shell:
![capture d ecran de 2017-12-07 01-48-36](https://user-images.githubusercontent.com/1771322/33693104-17870448-daf1-11e7-8aec-7103878fed5d.png)

**Comment by chistota** [comment]
Hello. Try 1.9.2

**Comment by ghost** [comment]
Hello, still blurred, same result.

**Comment by chistota** [comment]
Will fix later. There is a solution, but it affects other working environment. How do I let you know.

**Comment by chistota** [comment]
Try. 1.9.4

**Comment by ghost** [comment]
Fixed, it is displayed as intented.

Thank you :)
